### ISSUE TITLE
Make casing consistent for SInterval

### ISSUE THREAD

**Issue by kdheepak** [PMeira/dss_capi#24]
Currently this is in the header file:

```
    DSS_CAPI_V7_DLL double LoadShapes_Get_sInterval(void);
    DSS_CAPI_V7_DLL void LoadShapes_Set_Sinterval(double Value);
```

It can be changed to:

```
    DSS_CAPI_V7_DLL double LoadShapes_Get_SInterval(void);
    DSS_CAPI_V7_DLL void LoadShapes_Set_SInterval(double Value);
```

This is a low priority issue.

**Comment by PMeira** [comment]
Yep, that comes from the COM names:
```
    function Get_sInterval: Double; safecall;
    procedure Set_Sinterval(Value: Double); safecall;
```
I'll duplicate them to make them consistent and deprecate one of the pairs.

**Comment by PMeira** [comment]
Reopening as Free Pascal doesn't like the approach I used on Linux. The CI didn't fail when it should have, so I'll fix that too.

**Comment by PMeira** [comment]
It seems there is a bug in Free Pascal where it makes one of the symbols local when there are two functions with the same name but different casing. It works fine on Windows but breaks on Linux. To work around it, we would have to provide a whole custom linker script. I don't think that's worth it, so I just reverted the change and will rename the functions in 0.11. With that, 0.10.1 should be compatible with 0.10.0.
